In [35]:
import pandas as pd
import numpy as np
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import linear_kernel

In [48]:
movie = pd.read_csv("C:/Users/DELL/Downloads/movie_dataset.csv",delimiter=",",low_memory=False)
movie.head()

,index,budget,genres,homepage,id,keywords,original_language,original_title,overview,popularity,...,Unnamed: 1255,Unnamed: 1256,Unnamed: 1257,Unnamed: 1258,Unnamed: 1259,Unnamed: 1260,Unnamed: 1261,Unnamed: 1262,Unnamed: 1263,Unnamed: 1264
0,0,237000000,Action Adventure Fantasy Science Fiction,http://www.avatarmovie.com/,19995,culture clash future space war space colony so...,en,Avatar,"In the 22nd century, a paraplegic Marine is di...",150.437577,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,1,300000000,Adventure Fantasy Action,http://disney.go.com/disneypictures/pirates/,285,ocean drug abuse exotic island east india trad...,en,Pirates of the Caribbean: At World's End,"Captain Barbossa, long believed to be dead, ha...",139.082615,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,2,245000000,Action Adventure Crime,http://www.sonypictures.com/movies/spectre/,206647,spy based on novel secret agent sequel mi6,en,Spectre,A cryptic message from Bond’s past sends him o...,107.376788,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,3,250000000,Action Crime Drama Thriller,http://www.thedarkknightrises.com/,49026,dc comics crime fighter terrorist secret ident...,en,The Dark Knight Rises,Following the death of District Attorney Harve...,112.31295,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,4,260000000,Action Adventure Science Fiction,http://movies.disney.com/john-carter,49529,based on novel mars medallion space travel pri...,en,John Carter,"John Carter is a war-weary, former military ca...",43.926995,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [37]:
def get_title_from_index(index):
    return movie[movie.index == index]["title"].values[0]
def get_index_from_title(title):
    return movie[movie.title == title]["index"].values[0]

In [38]:
features = ['keywords','cast','genres','director']
def combination(row):
    return row['keywords']+" "+row['cast']+" "+row['genres']+" "+row['director']
for i in features:
    movie[i] = movie[i].fillna('') 

movie["combination"] = movie.apply(combination,axis=1)
movie.iloc[0].combination

'culture clash future space war space colony society Sam Worthington Zoe Saldana Sigourney Weaver Stephen Lang Michelle Rodriguez Action Adventure Fantasy Science Fiction James Cameron'

In [39]:
cv=TfidfVectorizer()
tfidf_matrix=cv.fit_transform(movie['combination'])
cosine_sim = linear_kernel(tfidf_matrix, tfidf_matrix)

In [58]:
indices=pd.Series(movie.index,index=movie['title'])
titles=movie['title']
def recommendations(title):
    idx = indices[title]
    sim_scores = list(enumerate(cosine_sim[idx]))
    sim_scores = sorted(sim_scores, key=lambda x: x[1], reverse=True)
    sim_scores = sim_scores[1:20]
    movie_indices = [i[0] for i in sim_scores]
    return titles.iloc[movie_indices]

In [60]:
recommendations('Avengers: Age of Ultron')

16                             The Avengers
26               Captain America: Civil War
80                               Iron Man 2
86      Captain America: The Winter Soldier
127                    Thor: The Dark World
516                                   X-Men
204                                      X2
183                                 Ant-Man
65                        X-Men: Apocalypse
175                     The Incredible Hulk
39                 The Amazing Spider-Man 2
47               X-Men: Days of Future Past
793                                Deadpool
34                    X-Men: The Last Stand
69                                 Iron Man
32                               Iron Man 3
875                             Superman II
4765                   The Image Revolution
170      Captain America: The First Avenger
Name: title, dtype: object